### ISSUE TITLE
Build LXC container - Faillure

### ISSUE THREAD

**Issue by sh4rknado** [maruos/blueprints#21]
HOST : DEBIAN 10
BUILD : BLUEPRINT DEBIAN

sudo ./build.sh -b debian -n stretch-container -- -r stretch -a arm64 --minimal
[*] Loading distro plugin...
[ DEBIAN ] loading...
[*] Building image...
[ DEBIAN ] bootstrapping rootfs...
debootstrap is /usr/sbin/debootstrap
Checking cache download in /var/cache/lxc/debian/rootfs-stretch-arm64 ... 
Copying rootfs to /home/zerocool/Android/maru/vendor/maruos/blueprints/out/stretch-container-intermediates/rootfs...Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.
update-rc.d: error: cannot find a LSB script for checkroot.sh
update-rc.d: error: cannot find a LSB script for umountfs
update-rc.d: error: cannot find a LSB script for hwclockfirst.sh
Creating SSH2 RSA key; this may take some time ...
2048 SHA256:5UFQ5hLAd6QXcpuj2LcUpU7v2axP1UOUancFFJGJNQY root@debian (RSA)
Creating SSH2 ECDSA key; this may take some time ...
256 SHA256:g9s7QkUUi8BGobM4+eDFPeuKqpMuApNtF+N0HDbKVF8 root@debian (ECDSA)
Creating SSH2 ED25519 key; this may take some time ...
256 SHA256:Inghmld4lB2/mgC+ZluhUVCUzhBq2sLP1+Eog8JgcNY root@debian (ED25519)
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.

Current default time zone: 'Etc/UTC'
Local time is now:      Mon May 18 07:57:03 UTC 2020.
Universal Time is now:  Mon May 18 07:57:03 UTC 2020.

lxc-create: stretch-container: confile.c: parse_line: 2367 Unknown configuration key "lxc.tty"
lxc-create: stretch-container: parse.c: lxc_file_for_each_line_mmap: 141 Failed to parse config file "/var/lib/lxc/stretch-container/config" at line "lxc.tty = 4"
lxc-create: stretch-container: tools/lxc_create.c: main: 331 Failed to create container stretch-container
[*] Cleaning up...
rm: cannot remove 'maru_0.1-1_all.deb': No such file or directory
make: [Makefile:31: clean] Error 1 (ignored)

**Comment by utzcoz** [comment]
@sh4rknado Maybe you can try to install docker and use `./build-with-docker.sh -b debian -n stretch-container -- -r stretch -a arm64 --minimal` to build it.
