### ISSUE TITLE
Add artifacts uploading post step for GitHub Actions

### ISSUE THREAD

**Issue by utzcoz** [maruos/blueprints#27]
Upload generated rootfs files to artifact.

**Comment by utzcoz** [comment]
@pdsouza We can download artifacts in https://github.com/maruos/blueprints/actions/runs/6517531575?pr=29 now.

**Comment by AscendNow-Tech** [comment]
Wow, nice! Thanks @utzcoz

**Comment by pdsouza** [comment]
Thanks @utzcoz! Very cool
